artifact_uri: file:///C:/Users/Tharindu/OneDrive/Desktop/All/Data%20Science/MLProjects/ML_FLOW/mlruns/0/dbed21ebd34841e58faf79b9e9df5c38/artifacts
end_time: 1704008833377
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: dbed21ebd34841e58faf79b9e9df5c38
run_name: suave-eel-45
run_uuid: dbed21ebd34841e58faf79b9e9df5c38
source_name: ''
source_type: 4
source_version: ''
start_time: 1704008823967
status: 3
tags: []
user_id: Tharindu
