artifact_uri: file:///C:/Users/Tharindu/OneDrive/Desktop/All/Data%20Science/MLProjects/ML_FLOW/mlruns/0/9a31be757a3e4fa699c11ee0aced0411/artifacts
end_time: 1703951641691
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9a31be757a3e4fa699c11ee0aced0411
run_name: beautiful-boar-154
run_uuid: 9a31be757a3e4fa699c11ee0aced0411
source_name: ''
source_type: 4
source_version: ''
start_time: 1703951639337
status: 3
tags: []
user_id: Tharindu
