artifact_uri: file:///C:/Users/Tharindu/OneDrive/Desktop/All/Data%20Science/MLProjects/ML_FLOW/mlruns/0/146542933f0b4f0f96b477fa035677aa/artifacts
end_time: 1704009158810
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 146542933f0b4f0f96b477fa035677aa
run_name: lyrical-snake-295
run_uuid: 146542933f0b4f0f96b477fa035677aa
source_name: ''
source_type: 4
source_version: ''
start_time: 1704009152401
status: 3
tags: []
user_id: Tharindu
